"use client";

import * as React from "react";

/**
 * M3 theme controller — manages BOTH axes of the Material 3 theme:
 *
 * 1. Color scheme (curated themes from src/lib/m3/themes.ts, OR a custom
 *    scheme generated by the Theme Builder from a seed color)
 *    → applied as `<html data-theme="…">` (baseline = attribute removed,
 *      custom = "custom" + injected CSS var blocks in <style id="m3-custom-scheme">)
 * 2. Light/dark mode ("light" | "dark" | "system")
 *    → applied as the `.dark` class on <html>
 *
 * Both persist to localStorage and are mirrored by the no-flash inline
 * script in src/app/layout.tsx. When mode === "system" the hook follows
 * the user's prefers-color-scheme, including live OS changes.
 */

import {
  generateScheme,
  schemeToCssVars,
  normalizeHex,
  normalizeVariant,
  type GeneratedScheme,
  type M3VariantId,
} from "@/lib/m3/theme-builder";

export type M3Mode = "light" | "dark" | "system";
export type M3LegacyTheme = "light" | "dark";

const COLOR_KEY = "m3-color-theme";
const MODE_KEY = "m3-mode";
const CUSTOM_KEY = "m3-custom-scheme";
const CUSTOM_STYLE_ID = "m3-custom-scheme";

/** Params that define a custom scheme. */
export interface CustomSchemeParams {
  seed: string;
  variant: M3VariantId;
  contrast: number;
}

/** Persisted shape: params + the RESOLVED light/dark role maps, so the
 *  no-flash inline script can rebuild the style tag without the color engine. */
export interface CustomSchemeState extends CustomSchemeParams {
  light: Record<string, string>;
  dark: Record<string, string>;
}

/** Read the persisted custom scheme (null when absent/corrupt). */
function readStoredCustomScheme(): CustomSchemeState | null {
  try {
    const raw = localStorage.getItem(CUSTOM_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CustomSchemeState;
    if (
      typeof parsed?.seed === "string" &&
      typeof parsed?.variant === "string" &&
      parsed.light &&
      parsed.dark
    ) {
      return parsed;
    }
  } catch {
    /* private mode / corrupt */
  }
  return null;
}

/** Create/update the <style id="m3-custom-scheme"> tag with the CSS blocks. */
export function injectCustomStyle(blocks: { lightBlock: string; darkBlock: string }) {
  let el = document.getElementById(CUSTOM_STYLE_ID) as HTMLStyleElement | null;
  if (!el) {
    el = document.createElement("style");
    el.id = CUSTOM_STYLE_ID;
    document.head.appendChild(el);
  }
  el.textContent = `${blocks.lightBlock}\n${blocks.darkBlock}`;
}

function removeCustomStyle() {
  document.getElementById(CUSTOM_STYLE_ID)?.remove();
}

function clearStoredCustomScheme() {
  try {
    localStorage.removeItem(CUSTOM_KEY);
  } catch {
    /* private mode */
  }
}

export function applyColorTheme(id: string) {
  const html = document.documentElement;
  if (!id || id === "baseline") html.removeAttribute("data-theme");
  else html.setAttribute("data-theme", id);
}

export function resolveDark(mode: M3Mode): boolean {
  if (typeof window === "undefined") return false;
  if (mode === "system") {
    return window.matchMedia("(prefers-color-scheme: dark)").matches;
  }
  return mode === "dark";
}

export function applyMode(mode: M3Mode): boolean {
  const dark = resolveDark(mode);
  document.documentElement.classList.toggle("dark", dark);
  return dark;
}

export interface UseM3ThemeResult {
  /** Active curated color scheme id ("baseline" | "ocean" | "emerald" | "coral").
   *  When a custom scheme is active this still holds the last curated id —
   *  the one restored by clearCustomTheme(). */
  colorTheme: string;
  setColorTheme: (id: string) => void;
  /** Active mode preference ("light" | "dark" | "system"). */
  mode: M3Mode;
  setMode: (mode: M3Mode) => void;
  /** Resolved dark state (mode === "system" follows the OS). */
  isDark: boolean;
  /** Active custom (Theme Builder) scheme, or null when a curated scheme is in use. */
  customScheme: CustomSchemeParams | null;
  /** Generate a scheme from a seed + variant + contrast and apply it site-wide. */
  applyCustomTheme: (seed: string, variant: M3VariantId, contrast: number) => boolean;
  /** Remove the custom scheme and restore the last curated theme. */
  clearCustomTheme: () => void;
  /** Legacy helpers kept for convenience. */
  theme: M3LegacyTheme;
  toggle: () => void;
}

export function useM3Theme(): UseM3ThemeResult {
  const [colorTheme, setColorThemeState] = React.useState("baseline");
  const [mode, setModeState] = React.useState<M3Mode>("system");
  const [isDark, setIsDark] = React.useState(false);
  const [customScheme, setCustomScheme] = React.useState<CustomSchemeParams | null>(null);
  // Ref mirror of colorTheme so clearCustomTheme (a stable callback) can
  // restore the last curated scheme without adding it as a dependency.
  const colorThemeRef = React.useRef("baseline");

  // Hydrate from localStorage + DOM (the inline script already applied them).
  React.useEffect(() => {
    let storedColor = "baseline";
    let storedMode: M3Mode = "system";
    try {
      storedColor = localStorage.getItem(COLOR_KEY) || "baseline";
      const m = localStorage.getItem(MODE_KEY);
      if (m === "light" || m === "dark" || m === "system") storedMode = m;
    } catch {
      /* private mode */
    }
    setColorThemeState(storedColor);
    colorThemeRef.current = storedColor;
    setModeState(storedMode);
    setIsDark(document.documentElement.classList.contains("dark"));
    // Custom scheme: the inline script already applied data-theme + style tag;
    // hydrate state (and re-apply idempotently in case the script was skipped).
    const storedCustom = readStoredCustomScheme();
    if (storedCustom) {
      document.documentElement.setAttribute("data-theme", "custom");
      injectCustomStyle(schemeToCssVars(storedCustom as unknown as GeneratedScheme));
      setCustomScheme({
        seed: storedCustom.seed,
        variant: normalizeVariant(storedCustom.variant) ?? "tonal-spot",
        contrast: storedCustom.contrast,
      });
    }
  }, []);

  // Follow OS changes while mode === "system".
  React.useEffect(() => {
    if (mode !== "system") return;
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => setIsDark(applyMode("system"));
    mq.addEventListener("change", onChange);
    return () => mq.removeEventListener("change", onChange);
  }, [mode]);

  const setColorTheme = React.useCallback(
    (id: string) => {
      // Selecting a curated theme always clears the custom one.
      clearStoredCustomScheme();
      removeCustomStyle();
      setCustomScheme(null);
      applyColorTheme(id);
      try {
        localStorage.setItem(COLOR_KEY, id);
      } catch {
        /* private mode */
      }
      colorThemeRef.current = id;
      setColorThemeState(id);
    },
    []
  );

  const applyCustomTheme = React.useCallback((seed: string, variant: M3VariantId, contrast: number) => {
    const normalizedSeed = normalizeHex(seed);
    if (!normalizedSeed) return false;
    const v = normalizeVariant(variant) ?? "tonal-spot";
    const c = Number.isFinite(contrast) ? Math.min(1, Math.max(0, contrast)) : 0;
    const generated = generateScheme(normalizedSeed, v, c);
    const blocks = schemeToCssVars(generated);
    const persisted: CustomSchemeState = {
      seed: normalizedSeed,
      variant: v,
      contrast: c,
      light: generated.light,
      dark: generated.dark,
    };
    try {
      localStorage.setItem(CUSTOM_KEY, JSON.stringify(persisted));
    } catch {
      /* private mode */
    }
    injectCustomStyle(blocks);
    document.documentElement.setAttribute("data-theme", "custom");
    setCustomScheme({ seed: normalizedSeed, variant: v, contrast: c });
    return true;
  }, []);

  const clearCustomTheme = React.useCallback(() => {
    clearStoredCustomScheme();
    removeCustomStyle();
    setCustomScheme(null);
    applyColorTheme(colorThemeRef.current);
  }, []);

  const setMode = React.useCallback((next: M3Mode) => {
    const dark = applyMode(next);
    try {
      localStorage.setItem(MODE_KEY, next);
    } catch {
      /* private mode */
    }
    setModeState(next);
    setIsDark(dark);
  }, []);

  const toggle = React.useCallback(() => {
    setMode(isDark ? "light" : "dark");
  }, [isDark, setMode]);

  return {
    colorTheme,
    setColorTheme,
    mode,
    setMode,
    isDark,
    customScheme,
    applyCustomTheme,
    clearCustomTheme,
    theme: isDark ? "dark" : "light",
    toggle,
  };
}
